parameters:
    gsf_url_tokenizer.tokenizer_class: GollumSF\UrlTokenizerBundle\Tokenizer\Tokenizer
    gsf_url_tokenizer.ckecker_class: GollumSF\UrlTokenizerBundle\Checker\Checker

services:
  
    ##########
    # Events #
    ##########
    
    gsf_url_tokenizer.tokenizer:
        class: "%gsf_url_tokenizer.tokenizer_class%"
        arguments:
            - "%gsf_url_tokenizer.configurations.secret%"

    gsf_url_tokenizer.ckecker:
        class: "%gsf_url_tokenizer.ckecker_class%"
        arguments:
            - "@gsf_url_tokenizer.tokenizer"