# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        public: false       # Allows optimizing the container by removing unused services; this also means
          # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.

    GollumSF\UrlTokenizerBundle\EventSubscriber\:
        resource: '../../EventSubscriber/*'
        tags:
            - { name: kernel.event_subscriber }

    GollumSF\UrlTokenizerBundle\Tokenizer\TokenizerInterface:
        class: GollumSF\UrlTokenizerBundle\Tokenizer\Tokenizer

    GollumSF\UrlTokenizerBundle\Checker\CheckerInterface:
        class: GollumSF\UrlTokenizerBundle\Checker\Checker

    GollumSF\UrlTokenizerBundle\Reflection\ControllerActionExtractorInterface:
        class: GollumSF\UrlTokenizerBundle\Reflection\ControllerActionExtractor